version: '3'

services:
  postgres:
    image: 'postgres:12.1'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=crud_serialization_bug_test
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

  server:
    build:
      context: .
    volumes:
      - /app/node_modules
      - .:/app
    depends_on:
      - postgres
